#!/bin/sh

echo "<!DOCTYPE html>
<html lang=\"de\">
<head>
    <meta charset=\"UTF-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <meta name=\"theme-color\" content=\"#000000\">
    <title>$2</title>
    <meta name=\"description\" content=\"Die collatz-collection ist eine Sammlung von Statistiken und einem zugehörigen Spiel über das Collatz-Problem.\">
    <link rel=\"stylesheet\" href=\"$1style.css\">
    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css\" integrity=\"sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc\" crossorigin=\"anonymous\">

    <link rel=\"shortcut icon\"
        type=\"image/x-icon\"
        href=\"$1logo.ico\">
    <link rel=\"icon\"
        type=\"image/x-icon\"
        sizes=\"32x32 64x64 96x96 128x128 160x160 192x192 224x224 256x256 288x288 320x320 352x352 384x384 416x416 448x448 480x480 512x512\"
        href=\"$1logo.ico\">
    <link rel=\"apple-touch-icon\"
        type=\"image/x-icon\"
        sizes=\"32x32 64x64 96x96 128x128 160x160 192x192 224x224 256x256 288x288 320x320 352x352 384x384 416x416 448x448 480x480 512x512\"
        href=\"$1logo.ico\">
</head>

<body>
    <script src=\"$1collatz.js\"></script>

    <header class=\"center-children header\">
        <a href=\"https://github.com/Amplus2/collatz-collection/\" style=\"text-decoration: none;\">
            <div class=\"sub-header\">
                <img class=\"logo\" src=\"logo.ico\"></img>
                <h1>collatz-collection</h1>
            </div>
        </a>
        <div class=\"nav_box\">
            <h3><a href=\"$1stats/\">Statistiken</a></h3>
            <h3><a href=\"$1game/\">Spiel</a></h3>
            <h3><a href=\"$1seq/\">Collatz-Folgen</a></h3>
            <h3><a href=\"$1graph/\">Graph</a></h3>
        </div>
    </header>

    <img src=\"$1kurs_logo.ico\" style=\"height: 85px; width: 85px; top: 15px; right: 15px; position: absolute;\">
    <img src=\"$1qr.png\" style=\"height: 85px; width: 85px; top: 15px; right: 115px; position: absolute;\">

$(cat)
</body>
</html>"
